# Numpy 3: Swap row 0 and 1 in the 3*3 numpy array.(Use indexing and slicing) Eg. Input [[1,2,3], [4,5,6], [7,8,9]] Output: [[4,5,6], [1,2,3], [7,8,9]]

In [2]:
import numpy as np

A = np.random.randint(1,9,(3,3))
A

array([[8, 5, 3],
       [3, 2, 7],
       [6, 6, 4]])

In [15]:
B = A[1::2]
C = A[::3]
D = A[2:]

In [16]:
B

array([[3, 2, 7]])

In [17]:
C

array([[8, 5, 3]])

In [19]:
D

array([[6, 6, 4]])

In [21]:
E = np.vstack((B,C,D))
E

array([[3, 2, 7],
       [8, 5, 3],
       [6, 6, 4]])

# Another code

In [22]:
import numpy as np

A = np.random.randint(1,9,(3,3))
A

array([[3, 6, 6],
       [6, 8, 2],
       [4, 6, 4]])

In [23]:
B = A[[1,0,2]]
B

array([[6, 8, 2],
       [3, 6, 6],
       [4, 6, 4]])

# Another code

In [34]:
import numpy as np

A = np.random.randint(1,9,(3,3))
A

array([[7, 5, 1],
       [5, 8, 2],
       [6, 5, 7]])

In [37]:
A[[0,1], :] = A[[1,0], :]

In [38]:
A

array([[7, 5, 1],
       [5, 8, 2],
       [6, 5, 7]])