# Numpy 2. Create Numpy array named "arr1" with numbers 1,2,3,....100. Replace all odd numbers in arr1 by -1. Expected output: Array([-1,2,-1,4,-1,6,........])

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(1,101)
arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [6]:
arr1[arr1%2!=0] = -1

In [7]:
arr1

array([ -1,   2,  -1,   4,  -1,   6,  -1,   8,  -1,  10,  -1,  12,  -1,
        14,  -1,  16,  -1,  18,  -1,  20,  -1,  22,  -1,  24,  -1,  26,
        -1,  28,  -1,  30,  -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,
        40,  -1,  42,  -1,  44,  -1,  46,  -1,  48,  -1,  50,  -1,  52,
        -1,  54,  -1,  56,  -1,  58,  -1,  60,  -1,  62,  -1,  64,  -1,
        66,  -1,  68,  -1,  70,  -1,  72,  -1,  74,  -1,  76,  -1,  78,
        -1,  80,  -1,  82,  -1,  84,  -1,  86,  -1,  88,  -1,  90,  -1,
        92,  -1,  94,  -1,  96,  -1,  98,  -1, 100])

In [9]:
import numpy as np

arr1 = np.arange(1,101)
print(arr1)

arr1[arr1%2!=0] = -1
arr1

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


array([ -1,   2,  -1,   4,  -1,   6,  -1,   8,  -1,  10,  -1,  12,  -1,
        14,  -1,  16,  -1,  18,  -1,  20,  -1,  22,  -1,  24,  -1,  26,
        -1,  28,  -1,  30,  -1,  32,  -1,  34,  -1,  36,  -1,  38,  -1,
        40,  -1,  42,  -1,  44,  -1,  46,  -1,  48,  -1,  50,  -1,  52,
        -1,  54,  -1,  56,  -1,  58,  -1,  60,  -1,  62,  -1,  64,  -1,
        66,  -1,  68,  -1,  70,  -1,  72,  -1,  74,  -1,  76,  -1,  78,
        -1,  80,  -1,  82,  -1,  84,  -1,  86,  -1,  88,  -1,  90,  -1,
        92,  -1,  94,  -1,  96,  -1,  98,  -1, 100])